IPN_TEST = {
    'notify_version ': '2.4',
    'last_name': 'Smith',
    'receiver_email': 'seller@paypalsandbox.com',
    'payment_status': '2',
    'mc_fee': '0.44',
    'tax': '2.02',
    'parent_txn_id ': '',
    'item_name1': 'something',
    'residence_country': '182',
    'invoice': 'abc1234',
    'address_state': 'CA',
    'payer_status': '0',
    'txn_type': 'cart',
    'address_street': '123, any street',
    'quantity1': '1',
    'payment_date': '22:56:14 Feb. 02, 2009 PST',
    'first_name': 'John',
    'item_number1': 'AK-1234',
    'item_name': '',
    'address_country': '182',
    'ipn_type': '4',
    'mc_gross1': '9.34',
    'custom': 'xyz123',
    'for_auction': '',
    'address_name': 'John Smith',
    'pending_reason': '',
    'item_number': '',
    'receiver_id': 'TESTSELLERID1',
    'reason_code': '',
    'business': '',
    'txn_id ': '1423656',
    'payer_id': 'TESTBUYERID01',
    'mc_handling1': '1.67',
    'notify_url': 'http://216.19.180.83:8000/ipn/',
    'auction_closing_date': '',
    'mc_handling': '2.06',
    'auction_buyer_id': '',
    'address_zip': '95131',
    'address_country_code': '182',
    'address_city': 'San Jose',
    'address_status': '1',
    'mc_shipping': '3.02',
    'cmd': '_send_ipn-session',
    'mc_currency': '15',
    'shipping': '',
    'payer_email': 'buyer@paypalsandbox.com',
    'payment_type': '1',
    'receipt_ID': '',
    'mc_gross': '',
    'mc_shipping1': '1.02',
    'quantity': ''
}


