# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-18 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipn', '0008_auto_20181128_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paypalipn',
            name='address_city',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='paypalipn',
            name='address_state',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
